name: Push coverage data to CodeCov

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  codecov:
    name: Push coverage data
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.5
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: "1.11.3"
          otp-version: "23"
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
        env:
          MIX_ENV: test
      - name: Setup environment
        run: mix legion.setup
        env:
          MIX_ENV: test
      - name: Run code coverage tool
        run: mix coveralls.json
        env:
          MIX_ENV: test
      - name: Push coverage data to the platform
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
